//
//  GlyphSequence.swift
//  GlyphHackPractice
//
//  Created by OhnoHiraku on 2015/03/26.
//  Copyright (c) 2015年 Hiraku Ohno. All rights reserved.
//

import UIKit

public enum GlyphSequenceCount:Int {
    case One    = 1
    case Two    = 2
    case Three  = 3
    case Four   = 4
    case Five   = 5
}

public class GlyphSequenceProvider: NSObject {
    
    public static func provideGlyphSequence(count: GlyphSequenceCount) -> [GlyphType] {
        let target: [[GlyphType]]?
        switch count {
        case .One:
            target = nil
        case .Two:
            target = GlyphSequenceProvider.twoItemsSequences
        case .Three:
            target = GlyphSequenceProvider.threeItemsSequences
        case .Four:
            target = GlyphSequenceProvider.fourItemsSequences
        case .Five:
            target = GlyphSequenceProvider.fiveItemsSequences
        }
        
        var index = Int(arc4random_uniform(UInt32(target!.count)))
        return target![index]
    }
   
    private static let singleItemsSequences:[[GlyphType]] = [[GlyphType.Abandon],
                                                             [GlyphType.Adapt],
                                                             [GlyphType.Adjust],
                                                             [GlyphType.Advance],
                                                             [GlyphType.After],
                                                             [GlyphType.Again],
                                                             [GlyphType.All],
                                                             [GlyphType.Answer],
                                                             [GlyphType.Attack],
                                                             [GlyphType.Avoid],
                                                             [GlyphType.Barrier],
                                                             [GlyphType.Begin],
                                                             [GlyphType.HumanA],
                                                             [GlyphType.Body],
                                                             [GlyphType.Breathe],
                                                             [GlyphType.Capture],
                                                             [GlyphType.Change],
                                                             [GlyphType.Chaos],
                                                             [GlyphType.Clear],
                                                             [GlyphType.CloseAll],
                                                             [GlyphType.Complex],
                                                             [GlyphType.Conflict],
                                                             [GlyphType.Consequence],
                                                             [GlyphType.Contemplate],
                                                             [GlyphType.Contract],
                                                             [GlyphType.Courage],
                                                             [GlyphType.Creation],
                                                             [GlyphType.CreativityB],
                                                             [GlyphType.Danger],
                                                             [GlyphType.Data],
                                                             [GlyphType.Defend],
                                                             [GlyphType.Destination],
                                                             [GlyphType.Destiny],
                                                             [GlyphType.Destruction],
                                                             [GlyphType.Deteriorate],
                                                             [GlyphType.Die],
                                                             [GlyphType.Difficult],
                                                             [GlyphType.Discover],
                                                             [GlyphType.Outside],
                                                             [GlyphType.Easy],
                                                             [GlyphType.End],
                                                             [GlyphType.EnlightenedA],
                                                             [GlyphType.EnlightenedB],
                                                             [GlyphType.Equal],
                                                             [GlyphType.Escape],
                                                             [GlyphType.Evolution],
                                                             [GlyphType.Failure],
                                                             [GlyphType.Fear],
                                                             [GlyphType.Follow],
                                                             [GlyphType.Forget],
                                                             [GlyphType.Future],
                                                             [GlyphType.Gain],
                                                             [GlyphType.Civilization],
                                                             [GlyphType.Grow],
                                                             [GlyphType.Harm],
                                                             [GlyphType.Harmony],
                                                             [GlyphType.Have],
                                                             [GlyphType.Help],
                                                             [GlyphType.Hide],
                                                             [GlyphType.Me],
                                                             [GlyphType.Ignore],
                                                             [GlyphType.Imperfect],
                                                             [GlyphType.Improve],
                                                             [GlyphType.Impure],
                                                             [GlyphType.Journey],
                                                             [GlyphType.Knowledge],
                                                             [GlyphType.Lead],
                                                             [GlyphType.Legacy],
                                                             [GlyphType.Less],
                                                             [GlyphType.Liberate],
                                                             [GlyphType.Lie],
                                                             [GlyphType.Live],
                                                             [GlyphType.Lose],
                                                             [GlyphType.MessageB],
                                                             [GlyphType.More],
                                                             [GlyphType.Mystery],
                                                             [GlyphType.Nature],
                                                             [GlyphType.New],
                                                             [GlyphType.Not],
                                                             [GlyphType.Nourish],
                                                             [GlyphType.Old],
                                                             [GlyphType.Open],
                                                             [GlyphType.OpenAll],
                                                             [GlyphType.Portal],
                                                             [GlyphType.Past],
                                                             [GlyphType.Path],
                                                             [GlyphType.Perfection],
                                                             [GlyphType.Perspective],
                                                             [GlyphType.Potential],
                                                             [GlyphType.Presence],
                                                             [GlyphType.Now],
                                                             [GlyphType.Purity],
                                                             [GlyphType.PursueA],
                                                             [GlyphType.Question],
                                                             [GlyphType.React],
                                                             [GlyphType.Rebel],
                                                             [GlyphType.Recharge],
                                                             [GlyphType.Resistance],
                                                             [GlyphType.Restraint],
                                                             [GlyphType.Retreat],
                                                             [GlyphType.Safety],
                                                             [GlyphType.Rescue],
                                                             [GlyphType.See],
                                                             [GlyphType.Search],
                                                             [GlyphType.SelfB],
                                                             [GlyphType.Separate],
                                                             [GlyphType.Shapers],
                                                             [GlyphType.Share],
                                                             [GlyphType.Simple],
                                                             [GlyphType.Soul],
                                                             [GlyphType.Stability],
                                                             [GlyphType.Strong],
                                                             [GlyphType.Together],
                                                             [GlyphType.Truth],
                                                             [GlyphType.Use],
                                                             [GlyphType.Victory],
                                                             [GlyphType.Want],
                                                             [GlyphType.Us],
                                                             [GlyphType.Weak],
                                                             [GlyphType.Worth],
                                                             [GlyphType.Xm],
                                                             [GlyphType.You]]
    
    private static let twoItemsSequences:[[GlyphType]] = [[GlyphType.Advance, GlyphType.EnlightenedA],
                                                          [GlyphType.Avoid, GlyphType.Conflict],
                                                          [GlyphType.Change, GlyphType.Now],
                                                          [GlyphType.Discover, GlyphType.Portal],
                                                          [GlyphType.Escape, GlyphType.Together],
                                                          [GlyphType.Follow, GlyphType.Journey],
                                                          [GlyphType.Gain, GlyphType.Safety],
                                                          [GlyphType.Hide, GlyphType.Truth],
                                                          [GlyphType.Nourish, GlyphType.Journey],
                                                          [GlyphType.OpenAll, GlyphType.Portal],
                                                          [GlyphType.Path, GlyphType.Harmony],
                                                          [GlyphType.Path, GlyphType.Perfection],
                                                          [GlyphType.Pure, GlyphType.Truth],
                                                          [GlyphType.Question, GlyphType.All],
                                                          [GlyphType.Question, GlyphType.Truth],
                                                          [GlyphType.Question, GlyphType.Attack],
                                                          [GlyphType.Search, GlyphType.Potential],
                                                          [GlyphType.Strong, GlyphType.CreativityB],
                                                          [GlyphType.Strong, GlyphType.Soul]]
    
    private static let threeItemsSequences: [[GlyphType]] = [[GlyphType.Adapt, GlyphType.HumanA, GlyphType.Weak],
                                                             [GlyphType.Advance, GlyphType.HumanA, GlyphType.EnlightenedA],
                                                             [GlyphType.Advance, GlyphType.HumanA, GlyphType.Resistance],
                                                             [GlyphType.Advance, GlyphType.Purity, GlyphType.Truth],
                                                             [GlyphType.Again, GlyphType.Journey, GlyphType.Outside],
                                                             [GlyphType.All, GlyphType.Civilization, GlyphType.Chaos],
                                                             [GlyphType.All, GlyphType.Xm, GlyphType.Liberate],
                                                             [GlyphType.Answer, GlyphType.Again, GlyphType.Avoid],
                                                             [GlyphType.Attack, GlyphType.Create, GlyphType.Danger],
                                                             [GlyphType.Attack, GlyphType.Destruction, GlyphType.Future],
                                                             [GlyphType.Attack, GlyphType.Difficult, GlyphType.Future],
                                                             [GlyphType.Attack, GlyphType.Shaper, GlyphType.Chaos],
                                                             [GlyphType.Attack, GlyphType.Shaper, GlyphType.Evolution],
                                                             [GlyphType.Attack, GlyphType.Shaper, GlyphType.Portal],
                                                             [GlyphType.Avoid, GlyphType.Attack, GlyphType.Chaos],
                                                             [GlyphType.Avoid, GlyphType.Chaos, GlyphType.Soul],
                                                             [GlyphType.Avoid, GlyphType.Complex, GlyphType.Conflict],
                                                             [GlyphType.Avoid, GlyphType.Complex, GlyphType.Soul],
                                                             [GlyphType.Avoid, GlyphType.Destiny, GlyphType.Lie],
                                                             [GlyphType.Avoid, GlyphType.Impure, GlyphType.Evolution],
                                                             [GlyphType.Avoid, GlyphType.Pure, GlyphType.Chaos],
                                                             [GlyphType.Avoid, GlyphType.Attack, GlyphType.Chaos],
                                                             [GlyphType.Capture, GlyphType.Shapers, GlyphType.Portal],
                                                             [GlyphType.Capture, GlyphType.Xm, GlyphType.Portal],
                                                             [GlyphType.Change, GlyphType.HumanA, GlyphType.Future],
                                                             [GlyphType.Civilization, GlyphType.Attack, GlyphType.Chaos],
                                                             [GlyphType.Complex, GlyphType.Journey, GlyphType.Future],
                                                             [GlyphType.Contemplate, GlyphType.Journey, GlyphType.Outside],
                                                             [GlyphType.Contemplate, GlyphType.Potential, GlyphType.Perfection],
                                                             [GlyphType.Contemplate, GlyphType.Potential, GlyphType.Journey],
                                                             [GlyphType.Contemplate, GlyphType.Potential, GlyphType.Perfection],
                                                             [GlyphType.Courage, GlyphType.Destiny, GlyphType.Rebel],
                                                             [GlyphType.Create, GlyphType.Future, GlyphType.Journey],
                                                             [GlyphType.Danger, GlyphType.Change, GlyphType.Past],
                                                             [GlyphType.Defend, GlyphType.Search, GlyphType.Safety],
                                                             [GlyphType.Destroy, GlyphType.Civilization, GlyphType.Danger],
                                                             [GlyphType.Destroy, GlyphType.Destiny, GlyphType.Barrier],
                                                             [GlyphType.Destroy, GlyphType.Difficult, GlyphType.Barrier],
                                                             [GlyphType.Destroy, GlyphType.Impure, GlyphType.Truth],
                                                             [GlyphType.Destroy, GlyphType.Weak, GlyphType.Civilization],
                                                             [GlyphType.Deteriorate, GlyphType.Advance, GlyphType.Now],
                                                             [GlyphType.Discover, GlyphType.Harmony, GlyphType.Equal],
                                                             [GlyphType.Discover, GlyphType.Portal, GlyphType.Truth],
                                                             [GlyphType.Discover, GlyphType.Pure, GlyphType.Truth],
                                                             [GlyphType.Discover, GlyphType.Resistance, GlyphType.Truth],
                                                             [GlyphType.Discover, GlyphType.Safety, GlyphType.Civilization],
                                                             [GlyphType.Discover, GlyphType.Shapers, GlyphType.Civilization],
                                                             [GlyphType.Discover, GlyphType.Shapers, GlyphType.EnlightenedA],
                                                             [GlyphType.Discover, GlyphType.Shapers, GlyphType.Lie],
                                                             [GlyphType.Discover, GlyphType.Shapers, GlyphType.Data],
                                                             [GlyphType.Escape, GlyphType.Impure, GlyphType.Evolution],
                                                             [GlyphType.Escape, GlyphType.Impure, GlyphType.Future],
                                                             [GlyphType.Escape, GlyphType.Impure, GlyphType.Truth],
                                                             [GlyphType.Escape, GlyphType.Portal, GlyphType.Harm],
                                                             [GlyphType.Escape, GlyphType.Shapers, GlyphType.Harm],
                                                             [GlyphType.Escape, GlyphType.Shapers, GlyphType.Harmony],
                                                             [GlyphType.Fear, GlyphType.Chaos, GlyphType.Xm],
                                                             [GlyphType.Fear, GlyphType.Complex, GlyphType.Xm],
                                                             [GlyphType.Follow, GlyphType.Pure, GlyphType.Journey],
                                                             [GlyphType.Future, GlyphType.Equal, GlyphType.Past],
                                                             [GlyphType.Gain, GlyphType.Civilization, GlyphType.Harmony],
                                                             [GlyphType.Gain, GlyphType.Future, GlyphType.Escape],
                                                             [GlyphType.Harm, GlyphType.Danger, GlyphType.Avoid],
                                                             [GlyphType.Harmony, GlyphType.Stability, GlyphType.Future],
                                                             [GlyphType.Hide, GlyphType.Journey, GlyphType.Truth],
                                                             [GlyphType.Hide, GlyphType.Path, GlyphType.Future],
                                                             [GlyphType.HumanA, GlyphType.Gain, GlyphType.Safety],
                                                             [GlyphType.Improve, GlyphType.Advance, GlyphType.Now],
                                                             [GlyphType.Improve, GlyphType.Future, GlyphType.Together],
                                                             [GlyphType.Improve, GlyphType.HumanA, GlyphType.Shapers],
                                                             [GlyphType.Not, GlyphType.CreativityB, GlyphType.Future],
                                                             [GlyphType.Not, GlyphType.Xm, GlyphType.Truth],
                                                             [GlyphType.Journey, GlyphType.Not, GlyphType.Soul],
                                                             [GlyphType.Lead, GlyphType.EnlightenedA, GlyphType.Civilization],
                                                             [GlyphType.Lead, GlyphType.Resistance, GlyphType.Question],
                                                             [GlyphType.Liberate, GlyphType.HumanA, GlyphType.Future],
                                                             [GlyphType.Liberate, GlyphType.Portal, GlyphType.Potential],
                                                             [GlyphType.Lose, GlyphType.Attack, GlyphType.Retreat],
                                                             [GlyphType.CreativityB, GlyphType.Body, GlyphType.Breathe],
                                                             [GlyphType.CreativityB, GlyphType.Equal, GlyphType.Truth],
                                                             [GlyphType.CreativityB, GlyphType.Open, GlyphType.Breathe],
                                                             [GlyphType.Nature, GlyphType.Purity, GlyphType.Defend],
                                                             [GlyphType.Nourish, GlyphType.CreativityB, GlyphType.Journey],
                                                             [GlyphType.Nourish, GlyphType.Xm, GlyphType.Portal],
                                                             [GlyphType.OpenAll, GlyphType.Portal, GlyphType.Evolution],
                                                             [GlyphType.OpenAll, GlyphType.Simple, GlyphType.Truth],
                                                             [GlyphType.Open, GlyphType.HumanA, GlyphType.Weak],
                                                             [GlyphType.Past, GlyphType.Equal, GlyphType.Future],
                                                             [GlyphType.Past, GlyphType.Harmony, GlyphType.Difficult],
                                                             [GlyphType.Past, GlyphType.Now, GlyphType.Future],
                                                             [GlyphType.Path, GlyphType.Harmony, GlyphType.Difficult],
                                                             [GlyphType.Harmony, GlyphType.Simple, GlyphType.Journey],
                                                             [GlyphType.Harmony, GlyphType.Stability, GlyphType.Future],
                                                             [GlyphType.Perfection, GlyphType.Past, GlyphType.Harmony],
                                                             [GlyphType.Potential, GlyphType.Truth, GlyphType.Harmony],
                                                             [GlyphType.Potential, GlyphType.Xm, GlyphType.Attack],
                                                             [GlyphType.Potential, GlyphType.Xm, GlyphType.Harmony],
                                                             [GlyphType.Potential, GlyphType.Xm, GlyphType.Attack],
                                                             [GlyphType.PursueA, GlyphType.Complex, GlyphType.Truth],
                                                             [GlyphType.PursueA, GlyphType.Purity, GlyphType.Body],
                                                             [GlyphType.Question, GlyphType.Conflict, GlyphType.Data],
                                                             [GlyphType.Question, GlyphType.Hide, GlyphType.Truth],
                                                             [GlyphType.Question, GlyphType.HumanA, GlyphType.Truth],
                                                             [GlyphType.Question, GlyphType.Shapers, GlyphType.Chaos],
                                                             [GlyphType.React, GlyphType.Impure, GlyphType.Civilization],
                                                             [GlyphType.React, GlyphType.Purity, GlyphType.Truth],
                                                             [GlyphType.Recharge, GlyphType.Nature, GlyphType.Perfection],
                                                             [GlyphType.Again, GlyphType.Journey, GlyphType.Outside],
                                                             [GlyphType.Retreat, GlyphType.Search, GlyphType.Safety],
                                                             [GlyphType.Search, GlyphType.Xm, GlyphType.Portal],
                                                             [GlyphType.See, GlyphType.Truth, GlyphType.Now],
                                                             [GlyphType.Separate, GlyphType.Future, GlyphType.Evolution],
                                                             [GlyphType.Separate, GlyphType.Future, GlyphType.PursueA],
                                                             [GlyphType.Together, GlyphType.Purity, GlyphType.Journey],
                                                             [GlyphType.Together, GlyphType.PursueA, GlyphType.Safety],
                                                             [GlyphType.Truth, GlyphType.Nourish, GlyphType.Soul],
                                                             [GlyphType.Want, GlyphType.Truth, GlyphType.Now],
                                                             [GlyphType.Want, GlyphType.Xm, GlyphType.Now],
                                                             [GlyphType.Attack, GlyphType.Attack, GlyphType.Chaos],
                                                             [GlyphType.Attack, GlyphType.Creation, GlyphType.Danger],
                                                             [GlyphType.Attack, GlyphType.Destruction, GlyphType.Future],
                                                             [GlyphType.Xm, GlyphType.Nourish, GlyphType.Civilization]]
    
    private static let fourItemsSequences:  [[GlyphType]] = [[GlyphType.Advance, GlyphType.Civilization, GlyphType.Again, GlyphType.Failure],
                                                             [GlyphType.Advance, GlyphType.Future, GlyphType.Not, GlyphType.Attack],
                                                             [GlyphType.All, GlyphType.Chaos, GlyphType.Not, GlyphType.Body],
                                                             [GlyphType.Attack, GlyphType.Civilization, GlyphType.Again, GlyphType.Failure],
                                                             [GlyphType.Attack, GlyphType.EnlightenedA, GlyphType.PursueA, GlyphType.Resistance],
                                                             [GlyphType.Attack, GlyphType.Future, GlyphType.Change, GlyphType.Destiny],
                                                             [GlyphType.Attack, GlyphType.Resistance, GlyphType.PursueA, GlyphType.EnlightenedA],
                                                             [GlyphType.Attack, GlyphType.Weak, GlyphType.Shapers, GlyphType.Lie],
                                                             [GlyphType.Avoid, GlyphType.Xm, GlyphType.Data, GlyphType.Lie],
                                                             [GlyphType.Breathe, GlyphType.Again, GlyphType.Journey, GlyphType.Again],
                                                             [GlyphType.Breathe, GlyphType.Nature, GlyphType.Perfection, GlyphType.Harmony],
                                                             [GlyphType.Capture, GlyphType.Fear, GlyphType.Discover, GlyphType.Courage],
                                                             [GlyphType.Change, GlyphType.Body, GlyphType.Improve, GlyphType.HumanA],
                                                             [GlyphType.Change, GlyphType.Future, GlyphType.Capture, GlyphType.Destiny],
                                                             [GlyphType.Change, GlyphType.HumanA, GlyphType.Potential, GlyphType.Use],
                                                             [GlyphType.Change, GlyphType.Simple, GlyphType.HumanA, GlyphType.Future],
                                                             [GlyphType.Chaos, GlyphType.Barrier, GlyphType.Shapers, GlyphType.Portal],
                                                             [GlyphType.Chaos, GlyphType.Destruction, GlyphType.Shapers, GlyphType.Portal],
                                                             [GlyphType.CloseAll, GlyphType.OpenAll, GlyphType.Discover, GlyphType.Truth],
                                                             [GlyphType.CloseAll, GlyphType.OpenAll, GlyphType.Gain, GlyphType.Truth],
                                                             [GlyphType.CloseAll, GlyphType.Open, GlyphType.CreativityB, GlyphType.Begin],
                                                             [GlyphType.Clear, GlyphType.CreativityB, GlyphType.Open, GlyphType.CreativityB],
                                                             [GlyphType.Complex, GlyphType.Shapers, GlyphType.Civilization, GlyphType.Strong],
                                                             [GlyphType.Contemplate, GlyphType.Complex, GlyphType.Shapers, GlyphType.Civilization],
                                                             [GlyphType.Contemplate, GlyphType.Complex, GlyphType.Shapers, GlyphType.Truth],
                                                             [GlyphType.Contemplate, GlyphType.Me, GlyphType.Path, GlyphType.Truth],
                                                             [GlyphType.Courage, GlyphType.Attack, GlyphType.Shapers, GlyphType.Future],
                                                             [GlyphType.Create, GlyphType.Outside, GlyphType.Impure, GlyphType.Path],
                                                             [GlyphType.Create, GlyphType.Future, GlyphType.Change, GlyphType.Destiny],
                                                             [GlyphType.Create, GlyphType.Future, GlyphType.Not, GlyphType.Attack],
                                                             [GlyphType.Create, GlyphType.Outside, GlyphType.Impure, GlyphType.Path],
                                                             [GlyphType.Defend, GlyphType.Data, GlyphType.Answer, GlyphType.CreativityB],
                                                             [GlyphType.Destruction, GlyphType.Complex, GlyphType.Shapers, GlyphType.Lie],
                                                             [GlyphType.Destruction, GlyphType.Destiny, GlyphType.HumanA, GlyphType.Lie],
                                                             [GlyphType.Deteriorate, GlyphType.HumanA, GlyphType.Weak, GlyphType.Rebel],
                                                             [GlyphType.Discover, GlyphType.Perfection, GlyphType.Safety, GlyphType.All],
                                                             [GlyphType.Outside, GlyphType.You, GlyphType.CreativityB, GlyphType.More],
                                                             [GlyphType.End, GlyphType.Journey, GlyphType.Discover, GlyphType.Destiny],
                                                             [GlyphType.Escape, GlyphType.Simple, GlyphType.HumanA, GlyphType.Future],
                                                             [GlyphType.Follow, GlyphType.Shapers, GlyphType.Portal, GlyphType.Data],
                                                             [GlyphType.Forget, GlyphType.Conflict, GlyphType.Adapt, GlyphType.Attack],
                                                             [GlyphType.Gain, GlyphType.Portal, GlyphType.Attack, GlyphType.Weak],
                                                             [GlyphType.Harmony, GlyphType.Path, GlyphType.Nourish, GlyphType.Now],
                                                             [GlyphType.Help, GlyphType.Gain, GlyphType.Create, GlyphType.PursueA],
                                                             [GlyphType.Help, GlyphType.Shapers, GlyphType.Create, GlyphType.Future],
                                                             [GlyphType.Hide, GlyphType.Impure, GlyphType.HumanA, GlyphType.CreativityB],
                                                             [GlyphType.HumanA, GlyphType.Have, GlyphType.Impure, GlyphType.Civilization],
                                                             [GlyphType.HumanA, GlyphType.Past, GlyphType.Now, GlyphType.Future],
                                                             [GlyphType.HumanA, GlyphType.Soul, GlyphType.Strong, GlyphType.Pure],
                                                             [GlyphType.Ignore, GlyphType.HumanA, GlyphType.Chaos, GlyphType.Lie],
                                                             [GlyphType.Improve, GlyphType.Body, GlyphType.CreativityB, GlyphType.Soul],
                                                             [GlyphType.Improve, GlyphType.Body, GlyphType.PursueA, GlyphType.Journey],
                                                             [GlyphType.Improve, GlyphType.CreativityB, GlyphType.Body, GlyphType.Not],
                                                             [GlyphType.Improve, GlyphType.CreativityB, GlyphType.Journey, GlyphType.Not],
                                                             [GlyphType.Not, GlyphType.CreativityB, GlyphType.Journey, GlyphType.Perfection],
                                                             [GlyphType.Not, GlyphType.CreativityB, GlyphType.Soul, GlyphType.Harmony],
                                                             [GlyphType.Journey, GlyphType.Not, GlyphType.Improve, GlyphType.Soul],
                                                             [GlyphType.Lead, GlyphType.Body, GlyphType.CreativityB, GlyphType.Soul],
                                                             [GlyphType.Lead, GlyphType.PursueA, GlyphType.React, GlyphType.Defend],
                                                             [GlyphType.Less, GlyphType.Chaos, GlyphType.More, GlyphType.Stability],
                                                             [GlyphType.Less, GlyphType.CreativityB, GlyphType.More, GlyphType.Soul],
                                                             [GlyphType.Less, GlyphType.Soul, GlyphType.More, GlyphType.CreativityB],
                                                             [GlyphType.Less, GlyphType.Truth, GlyphType.More, GlyphType.Chaos],
                                                             [GlyphType.Liberate, GlyphType.Xm, GlyphType.Portal, GlyphType.Together],
                                                             [GlyphType.Breathe, GlyphType.Again, GlyphType.Journey, GlyphType.Again],
                                                             [GlyphType.Breathe, GlyphType.Nature, GlyphType.Perfection, GlyphType.Harmony],
                                                             [GlyphType.Lose, GlyphType.Danger, GlyphType.Gain, GlyphType.Safety],
                                                             [GlyphType.More, GlyphType.CreativityB, GlyphType.Less, GlyphType.Soul],
                                                             [GlyphType.Not, GlyphType.CreativityB, GlyphType.Journey, GlyphType.Perfection],
                                                             [GlyphType.Nourish, GlyphType.Xm, GlyphType.Create, GlyphType.CreativityB],
                                                             [GlyphType.OpenAll, GlyphType.CloseAll, GlyphType.Discover, GlyphType.Truth],
                                                             [GlyphType.Open, GlyphType.Chaos, GlyphType.Not, GlyphType.Body],
                                                             [GlyphType.Past, GlyphType.Again, GlyphType.Now, GlyphType.Again],
                                                             [GlyphType.Harmony, GlyphType.Path, GlyphType.Nourish, GlyphType.Future],
                                                             [GlyphType.Harmony, GlyphType.Path, GlyphType.Nourish, GlyphType.Now],
                                                             [GlyphType.Perfection, GlyphType.Perfection, GlyphType.Safety, GlyphType.All],
                                                             [GlyphType.Portal, GlyphType.Change, GlyphType.Civilization, GlyphType.End],
                                                             [GlyphType.Portal, GlyphType.Die, GlyphType.Civilization, GlyphType.Die],
                                                             [GlyphType.Portal, GlyphType.Have, GlyphType.Truth, GlyphType.Data],
                                                             [GlyphType.Portal, GlyphType.Potential, GlyphType.Change, GlyphType.Future],
                                                             [GlyphType.Now, GlyphType.CreativityB, GlyphType.Journey, GlyphType.Perfection],
                                                             [GlyphType.Question, GlyphType.Truth, GlyphType.Gain, GlyphType.Future],
                                                             [GlyphType.Question, GlyphType.You, GlyphType.Impure, GlyphType.Civilization],
                                                             [GlyphType.Resistance, GlyphType.Defend, GlyphType.Shapers, GlyphType.Danger],
                                                             [GlyphType.Restraint, GlyphType.Fear, GlyphType.Avoid, GlyphType.Danger],
                                                             [GlyphType.Restraint, GlyphType.Path, GlyphType.Gain, GlyphType.Harmony],
                                                             [GlyphType.Rescue, GlyphType.HumanA, GlyphType.Potential, GlyphType.Use],
                                                             [GlyphType.Search, GlyphType.Data, GlyphType.Discover, GlyphType.Path],
                                                             [GlyphType.Search, GlyphType.Truth, GlyphType.Rescue, GlyphType.Civilization],
                                                             [GlyphType.Search, GlyphType.Xm, GlyphType.Rescue, GlyphType.Portal],
                                                             [GlyphType.Search, GlyphType.Data, GlyphType.Discover, GlyphType.Path],
                                                             [GlyphType.Search, GlyphType.Truth, GlyphType.See, GlyphType.Future],
                                                             [GlyphType.Search, GlyphType.Xm, GlyphType.Rescue, GlyphType.Portal],
                                                             [GlyphType.See, GlyphType.Truth, GlyphType.See, GlyphType.Future],
                                                             [GlyphType.Separate, GlyphType.Weak, GlyphType.Ignore, GlyphType.Truth],
                                                             [GlyphType.Shapers, GlyphType.Avoid, GlyphType.Purity, GlyphType.CreativityB],
                                                             [GlyphType.Shapers, GlyphType.Chaos, GlyphType.Purity, GlyphType.Harm],
                                                             [GlyphType.Shapers, GlyphType.Gain, GlyphType.Potential, GlyphType.Evolution],
                                                             [GlyphType.Shapers, GlyphType.Have, GlyphType.Strong, GlyphType.Path],
                                                             [GlyphType.Shapers, GlyphType.Lose, GlyphType.Potential, GlyphType.Evolution],
                                                             [GlyphType.Shapers, GlyphType.Data, GlyphType.End, GlyphType.Civilization],
                                                             [GlyphType.Shapers, GlyphType.CreativityB, GlyphType.Complex, GlyphType.Harmony],
                                                             [GlyphType.Shapers, GlyphType.Past, GlyphType.Now, GlyphType.Future],
                                                             [GlyphType.Shapers, GlyphType.Portal, GlyphType.CreativityB, GlyphType.Restraint],
                                                             [GlyphType.Shapers, GlyphType.See, GlyphType.Potential, GlyphType.Evolution],
                                                             [GlyphType.Simple, GlyphType.Civilization, GlyphType.Impure, GlyphType.Weak],
                                                             [GlyphType.Simple, GlyphType.Data, GlyphType.Complex, GlyphType.CreativityB],
                                                             [GlyphType.Simple, GlyphType.Truth, GlyphType.Breathe, GlyphType.Nature],
                                                             [GlyphType.Soul, GlyphType.Rebel, GlyphType.HumanA, GlyphType.Die],
                                                             [GlyphType.Stability, GlyphType.Pure, GlyphType.Breathe, GlyphType.Knowledge],
                                                             [GlyphType.Stability, GlyphType.Together, GlyphType.Defend, GlyphType.Truth],
                                                             [GlyphType.Strong, GlyphType.CreativityB, GlyphType.PursueA, GlyphType.Truth],
                                                             [GlyphType.Strong, GlyphType.Resistance, GlyphType.Capture, GlyphType.Portal],
                                                             [GlyphType.Strong, GlyphType.Together, GlyphType.Avoid, GlyphType.Attack],
                                                             [GlyphType.Avoid, GlyphType.Defend, GlyphType.Shapers, GlyphType.Danger],
                                                             [GlyphType.Avoid, GlyphType.Improve, GlyphType.HumanA, GlyphType.Soul],
                                                             [GlyphType.Together, GlyphType.Discover, GlyphType.Harmony, GlyphType.Equal],
                                                             [GlyphType.Truth, GlyphType.CreativityB, GlyphType.Discover, GlyphType.Xm],
                                                             [GlyphType.Use, GlyphType.Us, GlyphType.Follow, GlyphType.Us],
                                                             [GlyphType.Xm, GlyphType.Die, GlyphType.Chaos, GlyphType.Breathe],
                                                             [GlyphType.Xm, GlyphType.Have, GlyphType.CreativityB, GlyphType.Harmony],
                                                             [GlyphType.Xm, GlyphType.Have, GlyphType.CreativityB, GlyphType.Journey],
                                                             [GlyphType.You, GlyphType.Destiny, GlyphType.Not, GlyphType.Easy]]
    
    private static let fiveItemsSequences:  [[ GlyphType]] = [[GlyphType.Advance, GlyphType.Civilization, GlyphType.PursueA, GlyphType.Shapers, GlyphType.Path],
                                                              [GlyphType.Advance, GlyphType.Civilization, GlyphType.PursueA , GlyphType.Shapers, GlyphType.Truth],
                                                              [GlyphType.Answer, GlyphType.Question, GlyphType.Discover, GlyphType.Difficult, GlyphType.Truth],
                                                              [GlyphType.Attack, GlyphType.HumanA, GlyphType.Civilization, GlyphType.Xm, GlyphType.Data],
                                                              [GlyphType.Attack, GlyphType.Purity, GlyphType.Future, GlyphType.HumanA, GlyphType.Civilization],
                                                              [GlyphType.Attack, GlyphType.Purity, GlyphType.Future, GlyphType.Not, GlyphType.Attack],
                                                              [GlyphType.Attack, GlyphType.Separate, GlyphType.Path, GlyphType.End, GlyphType.Journey],
                                                              [GlyphType.Avoid, GlyphType.Chaos, GlyphType.Avoid, GlyphType.Shapers, GlyphType.Lie],
                                                              [GlyphType.Avoid, GlyphType.Chaos, GlyphType.Recharge, GlyphType.Potential, GlyphType.Attack],
                                                              [GlyphType.Avoid, GlyphType.Perfection, GlyphType.Stability, GlyphType.HumanA, GlyphType.Me],
                                                              [GlyphType.Breathe, GlyphType.Not, GlyphType.Xm, GlyphType.Lose, GlyphType.Me],
                                                              [GlyphType.Capture, GlyphType.Portal, GlyphType.Defend, GlyphType.Portal, GlyphType.Courage],
                                                              [GlyphType.Change, GlyphType.Separate, GlyphType.Past, GlyphType.End, GlyphType.Journey],
                                                              [GlyphType.Chaos, GlyphType.Attack, GlyphType.Conflict, GlyphType.Discover, GlyphType.Harmony],
                                                              [GlyphType.Chaos, GlyphType.Perfection, GlyphType.Stability, GlyphType.HumanA, GlyphType.Me],
                                                              [GlyphType.Chaos, GlyphType.Attack, GlyphType.Conflict, GlyphType.Discover, GlyphType.Harmony],
                                                              [GlyphType.CloseAll, GlyphType.CreativityB, GlyphType.Past, GlyphType.Now, GlyphType.Future],
                                                              [GlyphType.CloseAll, GlyphType.CreativityB, GlyphType.Liberate, GlyphType.Barrier, GlyphType.Body],
                                                              [GlyphType.Clear, GlyphType.CreativityB, GlyphType.Liberate, GlyphType.Barrier, GlyphType.Body],
                                                              [GlyphType.Contemplate, GlyphType.Future, GlyphType.Not, GlyphType.Shapers, GlyphType.Path],
                                                              [GlyphType.Contemplate, GlyphType.Restraint, GlyphType.Discover, GlyphType.More, GlyphType.Courage],
                                                              [GlyphType.Courage, GlyphType.Attack, GlyphType.Shapers, GlyphType.Portal, GlyphType.Together],
                                                              [GlyphType.Courage, GlyphType.Destroy, GlyphType.Shapers, GlyphType.Portal, GlyphType.Together],
                                                              [GlyphType.CreativityB, GlyphType.Purity, GlyphType.Future, GlyphType.HumanA, GlyphType.Civilization],
                                                              [GlyphType.CreativityB, GlyphType.Purity, GlyphType.Future, GlyphType.Not, GlyphType.Attack],
                                                              [GlyphType.Create, GlyphType.Separate, GlyphType.Path, GlyphType.End, GlyphType.Journey],
                                                              [GlyphType.Defend, GlyphType.Destiny, GlyphType.Defend, GlyphType.HumanA, GlyphType.Civilization],
                                                              [GlyphType.Defend, GlyphType.HumanA, GlyphType.Civilization, GlyphType.Portal, GlyphType.Data],
                                                              [GlyphType.Defend, GlyphType.HumanA, GlyphType.Civilization, GlyphType.Shapers, GlyphType.Lie],
                                                              [GlyphType.Defend, GlyphType.HumanA, GlyphType.Civilization, GlyphType.Shapers, GlyphType.Portal],
                                                              [GlyphType.Defend, GlyphType.HumanA, GlyphType.Civilization, GlyphType.Xm, GlyphType.Data],
                                                              [GlyphType.Destruction, GlyphType.Civilization, GlyphType.Now, GlyphType.Conflict, GlyphType.Attack],
                                                              [GlyphType.Destruction, GlyphType.Lie, GlyphType.Not, GlyphType.Gain, GlyphType.Soul],
                                                              [GlyphType.Outside, GlyphType.Me, GlyphType.Avoid, GlyphType.HumanA, GlyphType.Lie],
                                                              [GlyphType.Easy, GlyphType.Past, GlyphType.Future, GlyphType.Follow, GlyphType.Shapers],
                                                              [GlyphType.Escape, GlyphType.Body, GlyphType.Journey, GlyphType.Outside, GlyphType.Now],
                                                              [GlyphType.Forget, GlyphType.Attack, GlyphType.See, GlyphType.Outside, GlyphType.Harmony],
                                                              [GlyphType.Forget, GlyphType.Past, GlyphType.See, GlyphType.Now, GlyphType.Danger],
                                                              [GlyphType.Forget, GlyphType.Attack, GlyphType.Gain, GlyphType.Outside, GlyphType.Harmony],
                                                              [GlyphType.Gain, GlyphType.Truth, GlyphType.Open, GlyphType.HumanA, GlyphType.Soul],
                                                              [GlyphType.Harm, GlyphType.Evolution, GlyphType.PursueA, GlyphType.More, GlyphType.Attack],
                                                              [GlyphType.Help, GlyphType.EnlightenedA, GlyphType.Capture, GlyphType.All, GlyphType.Portal],
                                                              [GlyphType.Help, GlyphType.HumanA, GlyphType.Civilization, GlyphType.PursueA, GlyphType.Destiny],
                                                              [GlyphType.Help, GlyphType.Resistance, GlyphType.Capture, GlyphType.All, GlyphType.Portal],
                                                              [GlyphType.Hide, GlyphType.Resistance, GlyphType.Advance, GlyphType.Strong, GlyphType.Together],
                                                              [GlyphType.HumanA, GlyphType.Not, GlyphType.Together, GlyphType.Civilization, GlyphType.Deteriorate],
                                                              [GlyphType.HumanA, GlyphType.Shapers, GlyphType.Together, GlyphType.Creation, GlyphType.Destiny],
                                                              [GlyphType.Imperfect, GlyphType.Truth, GlyphType.Open, GlyphType.Complex, GlyphType.Answer],
                                                              [GlyphType.Imperfect, GlyphType.Xm, GlyphType.Data, GlyphType.HumanA, GlyphType.Chaos],
                                                              [GlyphType.Improve, GlyphType.CreativityB, GlyphType.Improve, GlyphType.Courage, GlyphType.Change],
                                                              [GlyphType.Not, GlyphType.CreativityB, GlyphType.Not, GlyphType.Soul, GlyphType.Harmony],
                                                              [GlyphType.Liberate, GlyphType.Portal, GlyphType.Liberate, GlyphType.HumanA, GlyphType.CreativityB],
                                                              [GlyphType.Liberate, GlyphType.Me, GlyphType.Liberate, GlyphType.HumanA, GlyphType.Civilization],
                                                              [GlyphType.Breathe, GlyphType.Not, GlyphType.Xm, GlyphType.Lose, GlyphType.Me],
                                                              [GlyphType.Lose, GlyphType.Shapers, GlyphType.Data, GlyphType.Gain, GlyphType.Chaos],
                                                              [GlyphType.CreativityB, GlyphType.Body, GlyphType.Soul, GlyphType.Purity, GlyphType.HumanA],
                                                              [GlyphType.More, GlyphType.Data, GlyphType.Gain, GlyphType.Portal, GlyphType.Advance],
                                                              [GlyphType.Old, GlyphType.Nature, GlyphType.Less, GlyphType.Strong, GlyphType.Now],
                                                              [GlyphType.Past, GlyphType.Barrier, GlyphType.Creation, GlyphType.Future, GlyphType.Journey],
                                                              [GlyphType.Past, GlyphType.Chaos, GlyphType.Creation, GlyphType.Future, GlyphType.Harmony],
                                                              [GlyphType.Past, GlyphType.Path, GlyphType.Creation, GlyphType.Future, GlyphType.Journey],
                                                              [GlyphType.Portal, GlyphType.Attack, GlyphType.Danger, GlyphType.PursueA, GlyphType.Safety],
                                                              [GlyphType.Portal, GlyphType.Barrier, GlyphType.Defend, GlyphType.HumanA, GlyphType.Shapers],
                                                              [GlyphType.Portal, GlyphType.Creation, GlyphType.Danger, GlyphType.PursueA, GlyphType.Safety],
                                                              [GlyphType.Portal, GlyphType.Improve, GlyphType.HumanA, GlyphType.Future, GlyphType.Civilization],
                                                              [GlyphType.Portal, GlyphType.Potential, GlyphType.Help, GlyphType.HumanA, GlyphType.Future],
                                                              [GlyphType.Now, GlyphType.Chaos, GlyphType.Creation, GlyphType.Future, GlyphType.Civilization],
                                                              [GlyphType.PursueA, GlyphType.Conflict, GlyphType.Advance, GlyphType.Attack, GlyphType.Chaos],
                                                              [GlyphType.PursueA, GlyphType.Conflict, GlyphType.Attack, GlyphType.Advance, GlyphType.Chaos],
                                                              [GlyphType.PursueA, GlyphType.Path, GlyphType.Outside, GlyphType.Shapers, GlyphType.Lie],
                                                              [GlyphType.Question, GlyphType.HumanA, GlyphType.Civilization, GlyphType.Destruction, GlyphType.Portal],
                                                              [GlyphType.Question, GlyphType.Less, GlyphType.Forget, GlyphType.All, GlyphType.Lie],
                                                              [GlyphType.React, GlyphType.Rebel, GlyphType.Question, GlyphType.Shapers, GlyphType.Lie],
                                                              [GlyphType.Rebel, GlyphType.CreativityB, GlyphType.Evolution, GlyphType.Destiny, GlyphType.Harmony],
                                                              [GlyphType.Rebel, GlyphType.CreativityB, GlyphType.Evolution, GlyphType.Destiny, GlyphType.Now],
                                                              [GlyphType.Recharge, GlyphType.Not, GlyphType.Recharge, GlyphType.HumanA, GlyphType.Soul],
                                                              [GlyphType.Recharge, GlyphType.Now, GlyphType.Recharge, GlyphType.HumanA, GlyphType.Soul],
                                                              [GlyphType.Recharge, GlyphType.Soul, GlyphType.Less, GlyphType.HumanA, GlyphType.Harm],
                                                              [GlyphType.Rescue, GlyphType.HumanA, GlyphType.Civilization, GlyphType.Destruction, GlyphType.Portal],
                                                              [GlyphType.Search, GlyphType.Destiny, GlyphType.Creation, GlyphType.Purity, GlyphType.Future],
                                                              [GlyphType.Separate, GlyphType.CreativityB, GlyphType.Body, GlyphType.Discover, GlyphType.EnlightenedA],
                                                              [GlyphType.Separate, GlyphType.Truth, GlyphType.Lie, GlyphType.Shapers, GlyphType.Future],
                                                              [GlyphType.Shapers, GlyphType.Lead, GlyphType.HumanA, GlyphType.Complex, GlyphType.Journey],
                                                              [GlyphType.Shapers, GlyphType.Portal, GlyphType.Data, GlyphType.Creation, GlyphType.Chaos],
                                                              [GlyphType.Shapers, GlyphType.Portal, GlyphType.Data, GlyphType.Destruction, GlyphType.Civilization],
                                                              [GlyphType.Shapers, GlyphType.See, GlyphType.Complex, GlyphType.Path, GlyphType.Destiny],
                                                              [GlyphType.Shapers, GlyphType.Want, GlyphType.HumanA, GlyphType.CreativityB, GlyphType.Future],
                                                              [GlyphType.Simple, GlyphType.Old, GlyphType.Truth, GlyphType.Journey, GlyphType.Not],
                                                              [GlyphType.Simple, GlyphType.Truth, GlyphType.Forget, GlyphType.Easy, GlyphType.Evolution],
                                                              [GlyphType.Simple, GlyphType.Truth, GlyphType.Shapers, GlyphType.Destruction, GlyphType.Civilization],
                                                              [GlyphType.Stability, GlyphType.Strong, GlyphType.Together, GlyphType.Defend, GlyphType.Resistance],
                                                              [GlyphType.Strong, GlyphType.Together, GlyphType.Attack, GlyphType.Together, GlyphType.Destiny],
                                                              [GlyphType.Use, GlyphType.CreativityB, GlyphType.Use, GlyphType.Courage, GlyphType.Change],
                                                              [GlyphType.Use, GlyphType.Restraint, GlyphType.Follow, GlyphType.Easy, GlyphType.Path],
                                                              [GlyphType.Use, GlyphType.Us, GlyphType.Creation, GlyphType.Shapers, GlyphType.Knowledge],
                                                              [GlyphType.Want, GlyphType.Truth, GlyphType.PursueA, GlyphType.Difficult, GlyphType.Path],
                                                              [GlyphType.Weak, GlyphType.HumanA, GlyphType.Destiny, GlyphType.Destruction, GlyphType.Civilization],
                                                              [GlyphType.Xm, GlyphType.Creation, GlyphType.Complex, GlyphType.HumanA, GlyphType.Destiny],
                                                              [GlyphType.Xm, GlyphType.Past, GlyphType.Future, GlyphType.Destiny, GlyphType.Harmony],
                                                              [GlyphType.Xm, GlyphType.Path, GlyphType.Future, GlyphType.Journey, GlyphType.Harmony]]
 }
              
